### ISSUE TITLE
使用MinIO时绑定域名功能不生效

### ISSUE THREAD

**Issue by MiaoToT** [halo-sigs/plugin-s3#12]
插件：plugin-s3
版本：1.2.1

问题：存储策略页面设置域名为api.test.com，桶名为blog，绑定域名为api.test.com/blog，最终发起的请求为blog.api.test.com(桶名+域名)。在使用MinIO时需要请求api.test.com/blog的路径，插件是不是不兼容MinIO。

配置：
![image](https://user-images.githubusercontent.com/34637577/212482767-fbe4bc63-2993-4e38-a113-32cb4d8ea8c2.png)

**Comment by longjuan** [comment]
s3支持Path-Style 与 Virtual Hosted-Style 两种风格，即`api.test.com/blog`和`blog.api.test.com`，在1.2.x版本中，为了兼容阿里oss，禁用了Path-Style，导致自建的minio不兼容。
但是使用ip访问能启用Path-Style，所以我没测试到绑定域名方式能否使用。
我还是提供一个设置项选择Path-Style 与 Virtual Hosted-Style用哪种。
/assign

**Comment by longjuan** [comment]
Hi @MiaoToT  ，最新的代码已修复minio兼容的相关问题，欢迎测试。
可在https://github.com/halo-sigs/plugin-s3/actions/runs/4039856684 最下面下载测试版（有效期一天），或者自己拉取最新源码编译。
如果可以用，我将发布新版本。
