### ISSUE TITLE
请问是否考虑在readme中添加适配 Cloudflare R2的描述?

### ISSUE THREAD

**Issue by SanQianQVQ** [halo-sigs/plugin-s3#16]
请问开发者是否考虑适配 Cloudflare R2?
主要在于 Cloudflare R2 提供免费的 10GB 存储额度，以及豁免流量费

**Comment by SanQianQVQ** [comment]
自己手动尝试了一下，可以正常使用本插件

**Comment by JohnNiang** [comment]
@SanQianQVQ ，如果有兴趣的话，欢迎修改 README 并提交 PR。

**Comment by SanQianQVQ** [comment]
@JohnNiang 已参照格式提交PR
https://github.com/halo-sigs/plugin-s3/pull/18

**Comment by longjuan** [comment]
没关联issue...
已在https://github.com/halo-sigs/plugin-s3/pull/18 完成
/close
