### ISSUE TITLE
成功上传，但无法读取

### ISSUE THREAD

**Issue by Eliaukilig** [halo-sigs/plugin-s3#28]
环境：halo2.3.2
部署方式：docker-compose

# 上传附件
![1678962705193](https://user-images.githubusercontent.com/117988843/225590839-94f19b81-dc35-45f0-b007-da57614f12ff.png)

# 预览附件
![1678962719509](https://user-images.githubusercontent.com/117988843/225590919-a5f68d34-850c-4feb-9bb4-7ba8ba4b3f26.png)

**Comment by Eliaukilig** [comment]
> 环境：Halo2.3.2 部署方式：docker-compose
> 
> # 上传附件
> ![1678962705193](https://user-images.githubusercontent.com/117988843/225590839-94f19b81-dc35-45f0-b007-da57614f12ff.png)
> 
> # 预览附件
> ![1678962719509](https://user-images.githubusercontent.com/117988843/225590919-a5f68d34-850c-4feb-9bb4-7ba8ba4b3f26.png)

存储平台是腾讯云cos

**Comment by Eliaukilig** [comment]
存储平台是腾讯云cos

**Comment by Eliaukilig** [comment]
这个插件上传到腾讯云cos的时候，获取到的链接似乎和腾讯云的链接并不相同

**Plugin s3**
![image](https://user-images.githubusercontent.com/117988843/225591760-00a957f3-9365-490e-b95a-4b9ae4125816.png)

**腾讯云cos**
![image](https://user-images.githubusercontent.com/117988843/225591920-f7efbe54-2bab-4b9f-a20c-a393dc5fc000.png)

应该是这个原因导致，但是并不清楚解决办法，非常感谢~

**Comment by longjuan** [comment]
我这边访问是AccessDenied
![image](https://user-images.githubusercontent.com/28662535/225596362-32585e46-0497-4893-adf3-c7348ebb4968.png)
你的桶应该是没开启公共读权限，所以显示加载异常。需要设置桶权限公共读或填写cdn地址。

**Comment by Eliaukilig** [comment]
十分感谢。
