### ISSUE TITLE
halo2.4版本不适配插件

### ISSUE THREAD

**Issue by MDQ0512** [halo-sigs/plugin-s3#31]
在附件页面点击修改配置会导致页面卡死

**Comment by JohnNiang** [comment]
看看是不是和这个问题一样。

**Comment by MDQ0512** [comment]
> 看看是不是和这个问题一样。
> 
> [Halo-dev/halo#3662](https://github.com/halo-dev/halo/issues/3662)

关闭插件看了一下，也是这种情况

**Comment by JohnNiang** [comment]
> > 看看是不是和这个问题一样。
> > 
> > [Halo-dev/halo#3662](https://github.com/halo-dev/halo/issues/3662)
> 
> 关闭插件看了一下，也是这种情况

这个问题已经在修了。等待发布 2.4.1。

**Comment by JohnNiang** [comment]
Hi @MDQ0512 ，建议升级到 2.4.1。

/triage duplicate

Close in favor of <https://github.com/halo-dev/halo/issues/3662>.

/close
