### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by eliaukilig** [halo-sigs/plugin-s3#34]
使用腾讯云cos的时候，提示上传失败
环境：halo2.4
搭建方式： mysql+docker compose

## 报错截图
![image](https://user-images.githubusercontent.com/117988843/231189454-d08a69a9-d464-4dac-b0fa-dfdcf6cc59c4.png)

## 参数配置
![image](https://user-images.githubusercontent.com/117988843/231189639-43655eab-04ee-473f-ac7a-eb0ad40df26e.png)

**Comment by eliaukilig** [comment]
抱歉，我尝试了一下重新配置，也尝试了使用阿里云的服务，也是出现了这个报错，并不清楚问题所在

**Comment by eliaukilig** [comment]
![Uploading image.png…]()
这里是配置了阿里云服务之后的报错截图

**Comment by eliaukilig** [comment]
这里问题解决了，解决方案是使用阿里云服务，腾讯云到最后也没成功解决。

**Comment by JohnNiang** [comment]
这里 https://github.com/halo-sigs/plugin-s3/issues/34#issuecomment-1503443195 提到的错误并不是 S3 抛出的，建议提供完整的日志，这样才能定位到具体的问题。

**Comment by eliaukilig** [comment]
这里目前已经解决了问题，当初的key和id是填反了的，不过是按着s3配置表明key和id来填的，尝试把它们反过来填之后解决了问题。
