### ISSUE TITLE
能否支持图片处理使用规则

### ISSUE THREAD

**Issue by kkkk24juastin** [halo-sigs/plugin-s3#36]
相册里面有些图片和视频比较大，想要处理一下放到博客上面。
类似于cos的规则< COS 域名>/image.jpg?<处理参数>，在连接后面在拼接一下就可以了。

**Comment by longjuan** [comment]
建议关注https://github.com/halo-dev/halo/issues/3994
在s3这边不太好做

**Comment by longjuan** [comment]
在 halo 最新2.7版本中支持了修改图片链接的功能，可以手动修改链接添加处理参数。
