### ISSUE TITLE
七牛云上传403报错

### ISSUE THREAD

**Issue by zhangfeibiao** [halo-sigs/plugin-s3#43]
**页面报错：**
<img width="659" alt="image" src="https://github.com/halo-sigs/plugin-s3/assets/34374831/70e54707-f94b-4ef0-9ab8-c91444a7ac2e">
**配置信息：**
![image](https://github.com/halo-sigs/plugin-s3/assets/34374831/3e2f99cb-888c-4368-81ed-a7cd9c9c5f38)
**报错日志：**
<img width="1131" alt="image" src="https://github.com/halo-sigs/plugin-s3/assets/34374831/2100de4a-0ddc-411b-b1e9-fba53827d119">

**Comment by longjuan** [comment]
403一般为账号/权限问题，请检查Bucket 桶名称、Access Key、Access Secret填写是否正确，并检查账号是否开通该桶的读写权限。

**Comment by zhouhuoya** [comment]
解决了吗？遇到了一样的问题

**Comment by longjuan** [comment]
> 解决了吗？遇到了一样的问题

请检查Bucket 桶名称、Access Key、Access Secret填写是否正确，并检查账号是否开通该桶的读写权限。
可以使用 S3Browser 验证账号及权限问题。

**Comment by zhouhuoya** [comment]
> > 解决了吗？遇到了一样的问题
> 
> 请检查Bucket 桶名称、Access Key、Access Secret填写是否正确，并检查账号是否开通该桶的读写权限。 可以使用 S3Browser 验证账号及权限问题。

这些都对的上，桶是公共桶

**Comment by longjuan** [comment]
@zhouhuoya 使用 S3Browser 能正常上传吗

**Comment by zhouhuoya** [comment]
> 

可以上传

**Comment by zhouhuoya** [comment]
> @zhouhuoya 使用 S3Browser 能正常上传吗

很奇怪，我在七牛云上的桶名称为blog
![image](https://github.com/halo-sigs/plugin-s3/assets/51031277/a81441c8-302e-47d0-bc8b-78e486c011f3)
但是通过s3看到的桶名称为
![image](https://github.com/halo-sigs/plugin-s3/assets/51031277/ade7062a-42ea-40dc-ba55-50c8ddf59c31)
然后我把桶名称改为这个就可以了

**Comment by longjuan** [comment]
https://developer.qiniu.com/kodo/4088/s3-access-domainname

> s3 空间名：全局唯一（遵循 s3 协议的要求）
> 
> 空间名称全局唯一时，s3 空间名=空间名称；空间名称全局不唯一时，系统会为空间自动生成一个 s3 空间名
> 七牛对象存储空间的 s3 空间名，可以通过 [Get Service](https://developer.qiniu.com/kodo/manual/4087/compatible-s3-api#service-operation) 接口获取，也可在 [开发者平台-对象存储-空间概览](https://portal.qiniu.com/bucket?ref=developer.qiniu.com&s_path=%2Fkodo%2F4088%2Fs3-access-domainname) 中查看

**Comment by zhouhuoya** [comment]
明白了  谢谢

**Comment by zhangfeibiao** [comment]
是的，七牛云的s3配置上，空间名称填写有点坑，并不是七牛后台面板上的空间名称，七牛对s3协议连接有一个系统命名的全局名称，也就是这个空间名称错误导致文件上传失败（访问拒绝错误）。
我要不提个PR完善下文档，不然其他人也可能踩坑
