### ISSUE TITLE
全新环境安装plugin-s3 Public插件halo后台报错， No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.请协助看下

### ISSUE THREAD

**Issue by leyedu** [halo-sigs/plugin-s3#5]
```java
2022-12-26T10:21:07.924+08:00  WARN 6 --- [oundedElastic-7] c.amazonaws.services.s3.AmazonS3Client   : No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors.
2022-12-26T10:21:08.001+08:00 ERROR 6 --- [oundedElastic-7] run.halo.s3os.S3OsAttachmentHandler      : Caught an SdkClientException, which means the client encountered a serious internal
problem while trying to communicate with S3ObjectStorage, such as not being able to access
the network.
Error message: The request to the service failed with a retryable reason, but resetting the request input stream has failed. See exception.getExtraInfo or debug-level logging for the original failure that caused this retry.;  If the request involves an input stream, the maximum stream buffer size can be configured via request.getRequestClientOptions().setReadLimit(int)

2022-12-26T10:21:08.002+08:00 ERROR 6 --- [oundedElastic-7] h.a.i.e.h.GlobalErrorWebExceptionHandler : The request to the service failed with a retryable reason, but resetting the request input stream has failed. See exception.getExtraInfo or debug-level logging for the original failure that caused this retry.;  If the request involves an input stream, the maximum stream buffer size can be configured via request.getRequestClientOptions().setReadLimit(int)

com.amazonaws.ResetException: The request to the service failed with a retryable reason, but resetting the request input stream has failed. See exception.getExtraInfo or debug-level logging for the original failure that caused this retry.;  If the request involves an input stream, the maximum stream buffer size can be configured via request.getRequestClientOptions().setReadLimit(int)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.resetRequestInputStream(AmazonHttpClient.java:1485) ~[na:na]
```

**Comment by leyedu** [comment]
![Uploading 企业微信截图_20221226103943.png…]()

**Comment by leyedu** [comment]
情况是：无论是ubuntu还是centos7/8，都不是无法上传附近，报错。太不应该了，那不成与腾讯服务器相冲命里

**Comment by longjuan** [comment]
你这个可能是对象存储配置信息填写错误，请检查endpoint、Access Key、Access Secret有没有填写错误

**Comment by hanfangyu** [comment]
有类似配置问题请教，以七牛云为例，endpoint写s3-cn-east-1.qiniucs.com，CDN域名写自己在七牛云的子域名（加速域名），这样对么

**Comment by longjuan** [comment]
> 有类似配置问题请教，以七牛云为例，endpoint写s3-cn-east-1.qiniucs.com，CDN域名写自己在七牛云的子域名（加速域名），这样对么

对的

**Comment by hanfangyu** [comment]
![image](https://user-images.githubusercontent.com/56426782/209524871-7316813c-6953-4869-ba15-e5836edc84a4.png)
![image](https://user-images.githubusercontent.com/56426782/209525017-9dedde3a-b11f-495c-a187-c9197bb2fe52.png)
但是报错了，麻烦帮忙看下~

**Comment by hanfangyu** [comment]
![image](https://user-images.githubusercontent.com/56426782/209525459-407f36ae-b706-4425-9e73-a5962b74fbfa.png)
![image](https://user-images.githubusercontent.com/56426782/209525520-4358dda9-3b15-45b6-b91b-2c89390fd3db.png)
这个是具体的配置

**Comment by longjuan** [comment]
@hanfangyu 请参考
![image](https://user-images.githubusercontent.com/28662535/209525916-aef15ce1-53e0-4a90-aa1a-bacad32d86a7.png)
![image](https://user-images.githubusercontent.com/28662535/209526015-ff690442-e33e-4ec4-82c3-56baab5c753a.png)

**Comment by hanfangyu** [comment]
对了下配置都一样的，还是报这个错
`com.amazonaws.services.s3.model.AmazonS3Exception: The bucket region not match with the service region. (Service: Amazon S3; Status Code: 400; Error Code: InCorrectRegion; Request ID: Xd8AAAAPJC6FSzQX; S3 Extended Request ID: null; Proxy: null)`

**Comment by hanfangyu** [comment]
![image](https://user-images.githubusercontent.com/56426782/209527868-b5fbec32-f01d-4ba5-91f4-3902770f34f6.png)
![image](https://user-images.githubusercontent.com/56426782/209527943-eed42ab9-72d7-42fe-9027-9df73635cef9.png)

好用了。原因是七牛云对象存储的存储区域必须和服务域名一致

**Comment by JohnNiang** [comment]
当前 issue 已经[解决](https://github.com/halo-sigs/plugin-s3/issues/5#issuecomment-1365008451)，我将关闭它。如果有任何问题，请随时重新打开 issue。

/close
