### ISSUE TITLE
配置了七牛云后，上传提示服务器错误

### ISSUE THREAD

**Issue by eliassama** [halo-sigs/plugin-s3#54]
<img width="672" alt="image" src="https://github.com/halo-sigs/plugin-s3/assets/79587688/1da54d6a-1d09-4d10-afbe-786a4a094f63">

**Comment by eliassama** [comment]
<img width="586" alt="image" src="https://github.com/halo-sigs/plugin-s3/assets/79587688/6a7571ee-679d-4f6c-8ca0-91f60861b38c">
两种 Endpoint 访问风格 都是过了，Region 不填写和 cn-east-1 也都试过了

**Comment by longjuan** [comment]
七牛云中空间名有可能和 s3 中的空间名不一致，若填写的不是 s3 空间名会报 403 错误。
可以看一下 halo 的日志，看看是否是403错误。
相关讨论：
* https://github.com/halo-sigs/plugin-s3/issues/43#issuecomment-1615398495

**Comment by eliassama** [comment]
> 七牛云中空间名有可能和 s3 中的空间名不一致，若填写的不是 s3 空间名会报 403 错误。 可以看一下 halo 的日志，看看是否是403错误。 相关讨论：
> 
> * [七牛云上传403报错 #43 (comment)](https://github.com/halo-sigs/plugin-s3/issues/43#issuecomment-1615398495)

找到问题了，我这个问题和空间名称无关，是因为在 endPoint 的最后面有一大堆空格，在七牛云复制的时候自动带上的。然后我以为 JAVA 或者前端会删除空格，实际不会。参考：https://stackoverflow.com/questions/18295759/java-lang-illegalargumentexception-illegal-character-in-authority-at-index-7-wh。可以考虑设置：
1. 如果填写空格不能提交。
2. 前端自动去除空格。
