### ISSUE TITLE
由于迁移插件缺少 object key annotation 导致迁移的数据调用 getPermalink 方法时会报错

### ISSUE THREAD

**Issue by guqing** [halo-sigs/plugin-s3#56]
see https://github.com/halo-sigs/plugin-migrate/issues/24
需要在 https://github.com/halo-sigs/plugin-s3/blob/23208009073fae1c76eacee58b0d89e54bbbce29/src/main/java/run/halo/s3os/S3OsAttachmentHandler.java#L145C28-L145C28 方法做一下兼容处理以解决旧数据问题，当获取不到 Object Key 时获取 `storage.halo.run/external-link` 作为 permalink 当获取不到时再抛异常，这样修改后需要注意检查删除功能是否正常

**Comment by JohnNiang** [comment]
/assign
/kind improvement

这里我会尝试兼容一下没有 object-key 的情况。
