### ISSUE TITLE
关于新增/编辑存储策略的小建议

### ISSUE THREAD

**Issue by OnlyTL** [halo-sigs/plugin-s3#58]
在添加或编辑存储策略时，可否在Access Key和Access Secret后面加上👀，点击显示填写的内容，现在只能看到隐藏的。无法判断填写的是否正确。
![image](https://github.com/halo-sigs/plugin-s3/assets/43626236/4cd00cae-607f-46ef-8a8d-6e9bde9d1098)

**Comment by longjuan** [comment]
@ruibaby ，有办法支持右侧眼睛来改变输入框类型吗

**Comment by longjuan** [comment]
请等待 Halo 2.9.0 的发布 :)
![image](https://github.com/halo-sigs/plugin-s3/assets/28662535/8171891c-205a-4906-9464-34cd980b81b9)
