### ISSUE TITLE
使用腾讯云oss时候遇到的问题，秘钥和秘钥id写反了

### ISSUE THREAD

**Issue by AchieveHF** [halo-sigs/plugin-s3#67]
设置中的标题命名的让人误解
Access Key = SecretId
Access Secret = SecretKey
希望修改为不会被误解的标题，也希望能帮助填写错误的人

**Comment by AccAutomaton** [comment]
可以参照阿里云的描述方式：
`Access Key ID`和`Access Key Secret`

**Comment by longjuan** [comment]
> 可以参照阿里云的描述方式：
> `Access Key ID`和`Access Key Secret`

改成这个如何？
/ping @halo-sigs/halo

**Comment by ruibaby** [comment]
> > 可以参照阿里云的描述方式：
> > `Access Key ID`和`Access Key Secret`
> 
> 改成这个如何？ /ping @halo-sigs/halo

可以，或许还可以添加一些 help 提示。

**Comment by longjuan** [comment]
@AccAutomaton 有兴趣来改一改吗?

**Comment by AccAutomaton** [comment]
> @AccAutomaton 有兴趣来改一改吗?

可以，考虑一下placeholder的措辞

**Comment by longjuan** [comment]
ChatGPT：

> 明白了，你想要提供简短而清晰的提示句子来帮助用户区分 "Access Key ID" 和 "Access Key Secret"。以下是一些可能的提示句子：
> 
> Access Key ID提示句子：
> 
> "Access Key ID是您身份的标识，类似于您的用户名。"
> "Access Key ID用于标识您的账户，像是一个用户名。"
> "Access Key ID用于唯一识别您的账户，类似于用户名。"
> Access Key Secret提示句子：
> 
> "Access Key Secret是一个秘密代码，需要保密，类似于您的密码。"
> "Access Key Secret是您账户的私密凭证，像是您的密码。"
> "Access Key Secret是用于验证身份的保密信息，类似于您的密码。"
> 这些句子应该可以帮助用户更好地理解 "Access Key ID" 和 "Access Key Secret" 的区别和用途。同时，提供这样的简短提示也可以降低用户填写错误的可能性。

**Comment by AccAutomaton** [comment]
@longjuan  `Access Key ID`是否有必要改成明文，以强调其功能类似于用户名

**Comment by AccAutomaton** [comment]
> @longjuan `Access Key ID`是否有必要改成明文，以强调其功能类似于用户名

看了下其他实现`Access Key ID`都是密文形式，还是不改了
